sudo: false

language: node_js

node_js:
  - "5.4"
  - "4.2"
  - "0.12"
  - "0.10"
  - "iojs"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/11d37f2a242720070853
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
